module advrf_interfaces {
  module srv {
    module dds_ {

      @final
      struct ListParameters_Request_
      {
        string prefix;
      };

      @final
      struct ListParameters_Response_
      {
        boolean success;
        sequence<string> names;
      };

    };
  };
};
