#include "../../rcl_interfaces/msg/RequestHeader.idl"

module advrf_interfaces {
  module srv {
    module dds_ {

      @final
      struct ListParameters_Request_
      {
        rcl_interfaces::msg::dds_::RequestHeader_ request_id;
        string prefix;
      };

      @final
      struct ListParameters_Response_
      {
        rcl_interfaces::msg::dds_::RequestHeader_ request_id;
        boolean success;
        sequence<string> names;
      };

    };
  };
};
