#pragma once

#include "../../std_msgs/msg/Header.idl"
#include "../../rcl_interfaces/msg/RequestHeader.idl"
#include "../../advrf_interfaces/msg/ReplCmdContent.idl"

module advrf_interfaces {
  module srv {
    module dds_ {

      @final
      struct ReplCmd_Request_
      {
        rcl_interfaces::msg::dds_::RequestHeader_ request_id;
        advrf_interfaces::msg::dds_::ReplCmd_Content_ request;
      };

      @final
      struct ReplCmd_Response_
      {
        rcl_interfaces::msg::dds_::RequestHeader_ request_id;
        std_msgs::msg::dds_::Header_ header;
        uint8 type;
        boolean success;
        string msg;
        string pdo;
      };

    };
  };
};
