<?xml version="1.0"?>
<package format="3">
  <name>advrf_cyclonedds_plugin</name>
  <version>0.1.0</version>
  <description>ECAT plugin implementation using CycloneDDS.</description>

  <maintainer email="hugo.pousseur@iit.it">Hugo POUSSEUR</maintainer>
  <maintainer email="manuel.delucchi@iit.it">Manuel Delucchi</maintainer>
  <license>TODO</license>

  <buildtool_depend>cmake</buildtool_depend>

  <depend>advrf_interfaces_dds</depend>
  <depend>advrf_dds_common</depend>
  <depend>advrf_interfaces_protobuf</depend>
  <depend>advrf_middleware_core</depend>
  <depend>advrf_cyclonedds_lib</depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>
