robot:
  name: kyon   # Robot name, used as a prefix for ROS2 node and topic names

  joints:

    # # Arm1
    # - name: shoulder_yaw_1
    #   ecat_id: 51
    # - name: shoulder_pitch_1
    #   ecat_id: 52
    # - name: elbow_pitch_1
    #   ecat_id: 53
    # - name: wrist_pitch_1
    #   ecat_id: 54
    # - name: wrist_yaw_1
    #   ecat_id: 55
    # - name: dagana_1_clamp_joint
    #   ecat_id: 101
    #   type: gripper

    # # Arm2
    # - name: shoulder_yaw_2
    #   ecat_id: 61
    # - name: shoulder_pitch_2
    #   ecat_id: 62
    # - name: elbow_pitch_2
    #   ecat_id: 63
    # - name: wrist_pitch_2
    #   ecat_id: 64
    # - name: wrist_yaw_2
    #   ecat_id: 65
    # - name: dagana_2_clamp_joint
    #   ecat_id: 102
    #   type: gripper

    # Leg1
    - name: hip_roll_1
      ecat_id: 1
    - name: hip_pitch_1
      ecat_id: 2
    - name: knee_pitch_1
      ecat_id: 3
    # - name: ankle_yaw_1
    #   ecat_id: 16
    # - name: wheel_joint_1
    #   ecat_id: 17

    # Leg2
    - name: hip_roll_2
      ecat_id: 4
    - name: hip_pitch_2
      ecat_id: 5
    - name: knee_pitch_2
      ecat_id: 6
    # - name: ankle_yaw_2
    #   ecat_id: 21
    # - name: wheel_joint_2
    #   ecat_id: 22

    # Leg3
    - name: hip_roll_3
      ecat_id: 7
    - name: hip_pitch_3
      ecat_id: 8
    - name: knee_pitch_3
      ecat_id: 9
    # - name: ankle_yaw_3
    #   ecat_id: 26
    # - name: wheel_joint_3
    #   ecat_id: 27

    # Leg4
    # - name: hip_roll_4
    #   ecat_id: 10
    # - name: hip_pitch_4
    #   ecat_id: 11
    # - name: knee_pitch_4
    #   ecat_id: 12
    # - name: ankle_yaw_4
    #   ecat_id: 31
    # - name: wheel_joint_4
    #   ecat_id: 32

  # imu:
  #   - name: imu_1
  #     ecat_id: 2
  
  # power_board:
  #   - name: power_board_1
  #     ecat_id: 71

  # pump:
  #   - name: pump_1
  #     ecat_id: 81

  # force_torque:
  #   - name: ft_1
  #     ecat_id: 91
  #   - name: ft_2
  #     ecat_id: 92

dds:
  domain: 42   # DDS/ROS 2 domain ID (default: 0)
