robot:
  name: kyon

joints:
    # Leg1
    - name: hip_roll_1
      ecat_id: 1
    - name: hip_pitch_1
      ecat_id: 2
    - name: knee_pitch_1
      ecat_id: 3

    # Leg2
    - name: hip_roll_2
      ecat_id: 4
    - name: hip_pitch_2
      ecat_id: 5
    - name: knee_pitch_2
      ecat_id: 6

    # Leg3
    - name: hip_roll_3
      ecat_id: 7
    - name: hip_pitch_3
      ecat_id: 8
    - name: knee_pitch_3
      ecat_id: 9

dds:
  namespace: advrf
  domain: 42
