<?xml version="1.0"?>
<package format="3">
  <name>advrf_middleware_docs</name>
  <version>0.1.0</version>

  <description>ADVRF Middleware documentation</description>

  <maintainer email="hugo.pousseur@iit.it">Hugo POUSSEUR</maintainer>
  <maintainer email="manuel.delucchi@iit.it">Manuel Delucchi</maintainer>
  <license>TODO</license>

  <build_depend>sphinx</build_depend>
  <build_depend>doxygen</build_depend>
  <build_depend>python3-breathe</build_depend>

  <export>
    <build_type>cmake</build_type>
  </export>
</package>