#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth0
  #eth_iface: enp2s0
  #eth_iface: enp3s0
  #eth_iface: enp33s0
  #eth_iface: enp35s0
  #eth_iface: enx0050b6121a50
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 500000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  sync_point_ns : 1500000
  power_off_boards : false
  reset_micro : true

ec_boards_base :
  app_mode : run_mode
  #app_mode : config_mode
  robot_name : NoNe
  read_SDOs : false
  use_pipes : true
  log_level : 1
  #fault_power_off : true
  use_ecat_pos_as_id : false
  pb_utils_verbose : false
 
zmq_pub :
  base_port : 9000
  #uri: "tcp://*:"
  uri: "ipc:///tmp/ecat_master:"
  fd_timeout_us : 100000 

zmq_rep :
  #uri: "tcp://*:5555"
  uri: "ipc:///tmp/ecat_master:5555"
  zmq_rcvtimeo_ms : 500
  #pipe_prefix : "/tmp/nrt_pipes/xddp/"
  pipe_prefix : "/proc/xenomai/registry/rtipc/xddp/"
  pb_utils_verbose : false
  
ati_config :
  ati_ip_addr : 192.168.1.1
  ft_ecat_pos : 1
  save_calib_matrix : false
  calib_mat_file : ../examples/ati_ft6_calib/data/ones.txt
  #calib_mat_file : ../examples/ati_ft6_calib/data/Calib_matrix_Cogimon_right_Foot_ft_147_sens8.txt
  dump_log : true

#############################
## GENERIC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

LpHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

HeriHandESC_X:
  sign: 1
  pos_offset: 0
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [100000.0 , 0.0 , 1.0]

CentAcESC_X:
  sign: 1
  pos_offset: 0
  max_current_A: 5.0
  enable_sandbox: false
  enable_pos_filter: false
  control_mode : 3B_motor_pos_ctrl
  pid :
    position: [220.0 , 0.0 , 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    #impedance:  [0.0, 0.0, 5.0, 0.01, 0.8]
    impedance:  [30.0, 5, 5.0, 0.01, 0.8]
   
Ft6Msp432ESC_X:
  analog_sample_freq_HZ: 20000
  aux_pdo : # names defined in SDO index 0x8002 
     wrd : [ "ts&&rtt" ]
  
AinMsp432ESC_X:
  analog_sample_freq_HZ: 1000
    
TestESC_X:
  upd_params :
    analog_sample_freq_Hz: 20000
  aux_pdo : # names defined in SDO index 0x8002 
     _rd :  [ pos_ref_fb ]
     _rd :  [ pos_ref_fb, motor_enc_warn, motor_enc_err, link_enc_warn, link_enc_err ]
     _rd :  [ iq_ref_fb, id_ref_fb ]
     _wr :  [ iq_ref ]
     _wrd : [ "iq_offset&&iq_out_fb" ]
     wrd : [ "ts&&rtt" ]
     
SynapticonESC_X:
  position_limits_rad:
    min: -3.1
    max: 3.1
  link_zero_incr: 0
  #control_mode: 3B_motor_pos_ctrl #esc.cpp --> controller_type_map
  #pid:
    #position: [0.0062845, 0.0 , 0.0 , 6.578719 , 311.577179] #3B_motor_pos_ctrl: 0: P_Pos, 1: I_Pos, 2: D_Pos, 3:P_Vel, 4:I_Vel
    #velocity: [10, 300 , 0.0 ] #71_motor_speed_ctrl, 0: P, 1: I, 2: D
    #current: [2000, 2000] #CC_current_ctrl: 0: Damping [mill, 1 --> 1000 mill], 1: Settling time [us]
    #torque: [0.06, 0, 0.006] # Torque control, Kp, Ki, Kd. LIMIT: [0.09, 0, 0.009]
