module advrf_interfaces {
  module msg {
    module dds_ {

      @final
      struct FoeMaster_
      {        
        string filename;
        uint32 password;
        string mcu_type;
        int32 slave_pos;
        int32 board_id;
      };

    };
  };
};
