#pragma once

module advrf_interfaces {
  module msg {
    module dds_ {
      struct ForceTorqueTxPdo_
      {
        int32 ecat_id;
        uint32 ts;
        uint32 op_idx_aux;
        float aux;
      };
    };
  };
};
