#pragma once

module advrf_interfaces {
  module msg {
    module dds_ {
      struct GripperTxPdo_
      {
        float target_pos;
        float target_vel;
        float target_torque;
        float gain_0;
        float gain_1;
        float gain_2;
        float gain_3;
        float gain_4;
      };

      struct GripperTxPdoVector_
      {
        sequence<GripperTxPdo_> data;
      };
    };
  };
};
