#pragma once

module advrf_interfaces {
  module msg {
        module dds_ {
            struct MotorXtTxPdo_
            {
                float pos_ref;
                float vel_ref;
                float tor_ref;
                float gain_0;
                float gain_1;
                float gain_2;
                float gain_3;
                float gain_4;
                unsigned long fault_ack;
                unsigned long ts;
                unsigned long op_idx_aux;
                float aux;
            };
            
            struct MotorXtTxPdo_Vector_
            {
                sequence<MotorXtTxPdo_> data;
            };
        };
    };
};
