#pragma once

module advrf_interfaces {
  module msg {
    module dds_ {
      struct PowerBoardTxPdo_
      {
        int32 ecat_id;
        uint32 master_command;
        uint32 fault_ack;
        uint32 op_idx_aux;
        float aux;
      };
    };
  };
};
