#pragma once

module advrf_interfaces {
  module msg {
    module dds_ {

      @final
      struct TrjStatus_
      {        
        uint8 queue_size;
        string running_trj;
      };

    };
  };
};
